Adds a RPI Pico Example: Azure_IoT_Hub_RPI_Pico
Azure/azure-sdk-for-c-arduino pull request #50
Opened 2022-12-31 10:19 UTC by djaus2

Based upon the ESP8266 example.
Only requires a few lines of code changes from that.

Note: Main branch readme for this project has code changes at bottom.

Nb: This replaces #49

2023-01-09 22:35 UTC, CIPop requested changes
Thank you for your contribution @djaus2!
We cannot offer support for this new sample since it is not using official RPI or Arduino SDKs.

Our recommendation is to create a separate repo within your account. Once that is set-up, we will add a link to our main `README.md` file to point to this community-supported, unofficial sample.

2023-01-09 22:35 UTC, CIPop commented on examples/Azure_IoT_Hub_RPI_Pico/readme.md
> +- I was given a [Freenove Basic Pico Starter Kit](https://github.com/Freenove/Freenove_Basic_Starter_Kit_for_Raspberry_Pi_Pico) and a [RPI Pico W](https://www.raspberrypi.com/documentation/microcontr
Please remove the starter kit reference, etc (things not relevant and potentially confusing for the sample).

2023-01-09 22:35 UTC, CIPop commented on examples/Azure_IoT_Hub_RPI_Pico/readme.md
> +- Ref: [https://freenove.com/fnk0058/](https://freenove.com/fnk0058/)
Please remove: let's keep instructions simple.

2023-01-09 22:35 UTC, CIPop commented on examples/Azure_IoT_Hub_RPI_Pico/readme.md
> +- Enter Pico in the searching box, and select ”Raspberry Pi Pico/RP2040” and click on [Install]
This is an unofficial package. Would using the official Arduino Mbed OS RP2040 Boards by Arduino work or does that not have WiFi support yet?

2023-01-09 22:35 UTC, CIPop commented on examples/Azure_IoT_Hub_RPI_Pico/readme.md
> +- Click Yes in the pop-up “dpinst-amd64.exe”installation window.
Please add the version this was last tested with (e.g. v2.7.0)

2023-01-09 22:35 UTC, CIPop commented on examples/Azure_IoT_Hub_RPI_Pico/readme.md
> +- Click Yes in the pop-up “dpinst-amd64.exe”installation window.
I did not get a pop-up for v2.7.0

2023-01-09 22:35 UTC, CIPop commented on examples/Azure_IoT_Hub_RPI_Pico/readme.md
> +- Click Tools>Board>Raspberry Pi RP2040 Boards>Raspberry Pi Pico.
Shouldn't this be Pi Pico __W__?

2023-01-09 22:35 UTC, CIPop commented on examples/Azure_IoT_Hub_RPI_Pico/readme.md
> +2.  Install the Azure SDK for Embedded C library.
Azure SDK for C

2023-01-09 22:35 UTC, CIPop commented on examples/Azure_IoT_Hub_RPI_Pico/readme.md
> +    -   Hover over the library item on the result list, then click on "Install".
Please include the version v2.8.0.

2023-01-09 22:35 UTC, CIPop commented on examples/Azure_IoT_Hub_RPI_Pico/readme.md
> +    -   Click on `azure_esp8266` to open the sample. <-- This needs to change when this is fomally merged into the original repository.
Please update

2023-01-09 22:35 UTC, CIPop commented on examples/Azure_IoT_Hub_RPI_Pico/readme.md
> +      -  **Alt** Open the azure esp8266 example as above and make the changes as [here]().
Please remove.

2023-01-09 22:35 UTC, CIPop commented on examples/Azure_IoT_Hub_RPI_Pico/Azure_IoT_Hub_RPI_Pico.ino
> +#define LED_PIN 2
Use LED_BUILTIN instead. Current configuration won't work on a RP2040 board.

2023-01-15 12:02 UTC, djaus2 commented on examples/Azure_IoT_Hub_RPI_Pico/readme.md
> +- Enter Pico in the searching box, and select ”Raspberry Pi Pico/RP2040” and click on [Install]
Doesn't have WiFi

2023-01-15 12:03 UTC, djaus2 commented on examples/Azure_IoT_Hub_RPI_Pico/readme.md
> +- Click Yes in the pop-up “dpinst-amd64.exe”installation window.
IDE V2.03

2023-01-18 16:26 UTC, CIPop commented
Closing PR with the following recommendation:

> Our recommendation is to create a separate repo within your account. Once that is set-up, we will add a link to our main README.md file to point to this community-supported, unofficial sample.

2023-01-18 16:26 UTC, closed without merging

2023-01-27 11:45 UTC, djaus2 commented
I'll make those changes but I also have been working on a signifcant port of the complete (as much is possible) of the Azure SDK for Embedded C functionality so when that is complete I'll link that.